"""empty message

Revision ID: 5e4bfc51dc39
Revises: b87eaeb11536
Create Date: 2024-12-18 15:28:16.965039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4bfc51dc39'
down_revision = 'b87eaeb11536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=120), nullable=True))
        batch_op.alter_column('preference',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('reference_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('reference_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('preference',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
